language: php
dist: xenial
sudo: false

matrix:
    include:
        - php: 7.1
          env: SYMFONY_VERSION="4.4.*" COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.4
          env: SYMFONY_VERSION="5.1.*" CHECK_CS=1
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer self-update
    - composer require --no-update symfony/config=$SYMFONY_VERSION symfony/http-kernel=$SYMFONY_VERSION symfony/dependency-injection=$SYMFONY_VERSION symfony/options-resolver=$SYMFONY_VERSION
    - composer require --no-update --dev symfony/framework-bundle=$SYMFONY_VERSION symfony/yaml=$SYMFONY_VERSION
    - composer update $COMPOSER_FLAGS --prefer-dist

script:
    - stty cols 120
    - if [ "$CHECK_CS" == 1 ]; then wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.16.7/php-cs-fixer.phar && php php-cs-fixer.phar fix --dry-run --diff; fi
    - vendor/bin/simple-phpunit
